proyecto_vehiculos/proyecto_vehiculos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('vehiculo.urls')),    
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]

proyecto_vehiculos/vehiculo/urls.py
from django.urls import path
from . import views

app_name = 'vehiculo'

urlpatterns = [    
    path('', views.index, name='vehiculo_index'),
    path('vehiculo/add/', views.add_vehiculo, name='add_vehiculo'),
    path('vehiculo/list/', views.list_vehiculos, name='list_vehiculos'),    
]

proyecto_vehiculos/vehiculo/models.py
from django.db import models

class Vehiculo(models.Model):
    MARCA_CHOICES = [
        ('Fiat', 'Fiat'),
        ('Chevrolet', 'Chevrolet'),
        ('Ford', 'Ford'),
        ('Toyota', 'Toyota'),
    ]
    CATEGORIA_CHOICES = [
        ('Particular', 'Particular'),
        ('Transporte', 'Transporte'),
        ('Carga', 'Carga'),
    ]

    marca = models.CharField(
        max_length=20,
        choices=MARCA_CHOICES,
        default='Ford'
    )
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50, unique=True)
    serial_motor = models.CharField(max_length=50, unique=True)
    categoria = models.CharField(
        max_length=20,
        choices=CATEGORIA_CHOICES,
        default='Particular'
    )
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.marca} {self.modelo}"

proyecto_vehiculos/vehiculo/forms.py
from django import forms
from .models import Vehiculo

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['marca', 'modelo', 'serial_carroceria', 'serial_motor', 'categoria', 'precio']

proyecto_vehiculos/vehiculo/views.py
"""FINAL DRILLING MODULO 6 
VENTA VIRTUAL DE VEHÍCULOS
Marcelo Aceituno | Python 0079"""
from .forms import VehiculoForm
from django.shortcuts import render, redirect
from .models import Vehiculo
from django.contrib.auth.decorators import permission_required, login_required


"""Funcion para la pagina de inico index.html
ruta http://127.0.0.1:8000/"""
def index(request):       
    return render(request, 'vehiculo/index.html')



"""Funcion para agregar vehiculos si el ususario esta con permiso o autenticado
ruta http://127.0.0.1:8000/vehiculo/add"""
@login_required()
@permission_required('vehiculo.add_vehiculo', raise_exception=True)
def add_vehiculo(request):
    if request.method == 'POST':
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('vehiculo:list_vehiculos')  # Cambia esto a la ruta deseada
    else:
        form = VehiculoForm()
    return render(request, 'vehiculo/add_vehiculo.html', {'form': form})    
    


"""Funcion para listar los vehiculos si el ususario esta con permiso o autenticado
ruta http://127.0.0.1:8000/vehiculo/list"""
@login_required()
@permission_required('vehiculo.view_vehiculo', raise_exception=True)
def list_vehiculos(request):
    vehiculos = Vehiculo.objects.all()
    return render(request, 'vehiculo/list_vehiculos.html', {'vehiculos': vehiculos})


def login(request):
    return render(request, 'vehiculo/login.html')


"""Funcion para logout de la aplicacion
ruta http://127.0.0.1:8000/logout"""
# @login_required()
# def salir(request):
#     logout(request)
#     return redirect('/')

proyecto_vehiculos/vehiculo/templates/vehiculo/add_vehiculo.html
{% extends 'vehiculo/base.html' %}

{% block title %}Vehiculos{% endblock %}

{% block content %}

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-4">
            <h3 class="text-center">Agregar Vehiculo</h3>
            <form method="post" class="mt-3">
                {% csrf_token %}
                {{ form.as_p }}                
                <button type="submit" class="btn btn-primary mt-2">Enviar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

proyecto_vehiculos/vehiculo/templates/vehiculo/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vehiculos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>

    {% include 'vehiculo/navbar.html' %}    

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
</html>

proyecto_vehiculos/vehiculo/templates/vehiculo/index.html
{% extends 'vehiculo/base.html' %}

{% block title %}Vehiculos{% endblock %}

{% block content %}    
    <div class="container d-flex justify-content-center align-items-center">
        <h1>Catálogo de Vehículos</h1><br>        
    </div>  
{% endblock %}

proyecto_vehiculos/vehiculo/templates/vehiculo/list_vehiculos.html
{% extends 'vehiculo/base.html' %}

{% block title %}Vehiculos{% endblock %}

{% block content %}

<h3>Listado de Vehículos</h3>

<!-- Mostrar el botón "Agregar" solo si el usuario tiene el permiso 
{% if puede_agregar %}
<a href="{% url 'vehiculo:add_vehiculo' %}">Agregar Vehículo</a>
{% endif %}-->

<table class="table">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Serial Carroceria</th>
            <th>Serial Motor</th>
            <th>Categoria</th>
            <th>Precio</th>
            <th>Condición de Precio</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
    {% for vehiculo in vehiculos %}
    <tr>
        <td>{{ vehiculo.marca }}</td>
        <td>{{ vehiculo.modelo }}</td>
        <td>{{ vehiculo.serial_carroceria }}</td>
        <td>{{ vehiculo.serial_motor }}</td>
        <td>{{ vehiculo.categoria }}</td>
        <td>{{ vehiculo.precio }}</td>
        {% if vehiculo.precio < 10000 %} <td>Bajo</td>
            {% elif vehiculo.precio >= 10000 and vehiculo.precio <= 30000 %} <td>Medio</td>
                {% else %}
                <td>Alto</td>
                {% endif %}

    </tr>
    {% endfor %}
    </tbody>
    
</table>

{% endblock %}

proyecto_vehiculos/vehiculo/templates/vehiculo/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'vehiculo:vehiculo_index' %}">Vehículos</a>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'vehiculo:vehiculo_index' %}">
                Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'vehiculo:add_vehiculo' %}">Agregar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'vehiculo:list_vehiculos' %}">Listar</a>
          </li>
        </ul>        
        
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Salir</a>
            </li>
            <li class="nav-item">
                <span class="nav-link disabled">Hola, {{ user.username }}</span>
            </li>
            {% else %}
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>

      </div>
    </div>
</nav>